name: downloads_path_provider
description: Flutter plugin to get the download directory for Android.
version: 0.1.0
author: jld3103 <pub@2bad2c0.de>
homepage: https://github.com/jld3103/downloads_path_provider

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: it.nplace.downloadspathprovider
    pluginClass: DownloadsPathProviderPlugin
